#! /bin/bash -ex

component="$(dirname "$0")"/..
cd "$component"
bin=../node_modules/.bin

"$bin"/browserify \
  build/bundle/timer-controls.js \
  --outfile=../public/components/timer-controls/script.js
