#! /bin/bash -ex

scripts="$(dirname "$0")"
component="$scripts"/..
cd "$component"
bin=../node_modules/.bin

"$bin"/elm-live \
  source/Main.elm \
  --output=build/bundle/elm.js \
  --warn \
  --dir=preview \
  --path-to-elm-make="$bin"/elm-make \
  --port=3081 \
  --before-build=scripts/styles \
  "$@"
