#! /bin/bash -ex

scripts="$(dirname "$0")"
local="$scripts"/../node_modules/.bin

"$local"/elm-live \
  source/Main.elm \
  --output=public/bundle.js \
  --warn \
  --dir=public \
  --path-to-elm-make="$local"/elm-make \
  --port=3081 \
  --before-build="$scripts"/styles \
  "$@"
