#! /bin/bash -ex

scripts="$(dirname "$0")"
component="$scripts"/..
local="$component"/node_modules/.bin

cd "$component"
"$local"/elm-live \
  source/Main.elm \
  --output=build/bundle/elm.js \
  --warn \
  --dir=preview \
  --path-to-elm-make="$local"/elm-make \
  --port=3081 \
  --before-build="$scripts"/styles \
  --after-build="$scripts"/bundle \
  "$@"
