#! /bin/bash -ex

local="$(dirname "$0")"/../node_modules/.bin

"$local"/elm-live \
  source/Main.elm \
  --output=public/bundle.js \
  --dir=public \
  --path-to-elm-make="$local"/elm-make \
  --port=3081 \
  "$@"
